version: '3'
services:
  node:
    build: .
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    networks:
      - my-network
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - ./log:/usr/app/log
  postgres:
    build: ./database
    restart: on-failure
    networks:
      - my-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
networks:
  my-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
  log: