version: '3'
services:
  docker-basics-nodejs:
    build: .
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    networks:
      - my-network
    volumes:
      - logs:/src/logs
    depends_on:
      - postgres
  postgres:
    build: ./database/
    restart: on-failure
    networks:
      - my-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/src/db_data
networks:
  my-network:
    driver: bridge
volumes:
  logs:
  db-data:
