version: '3'
services:
  app:
    build: .
    image: node_app
    restart: on-failure
    ports:
    - ${PORT}:${DOCKER_PORT}
    volumes:
      - logs:/src/logs
  db:
    image: "postgres:latest"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/src/db_data
volumes:
  logs:
  db-data: